[package]
name = "ddcd"
version = "0.1.0"
authors = ["Michael Zimmermann <sigmaepsilon92@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
ddcutil = { path="../ddcutil" }
tokio = { version="^1.1", features=["io-util", "macros", "net", "rt"] }
listenfd = "0.3"
thiserror = "^1.0"
